<form method="link" action="shoesproject.php"><input type="submit" value="Interactive Version"></form><br/><hr/>
<b>Sole (Learning Space)</b><br/><br/>My learning space is in a Quiet Room, Computer Lab or in my own personal bedroom.<br/>A quiet room helps me concentrate and stay on task.<br/>The computer lab aids me in research and relaxation.<br/>My own room is quiet so I can concentrate and has a computer so I can research and relax.<br/><hr/>
<b>Tongue (Favorite Ways to Work)</b><br/><br/>My favorite ways to work is to be creative,<br/> do something no one has done before, new and interesting.<br/>But when it comes to words and vocabulary I just memorize it.<br/>I do creative things because they are challenging and most of the time no one has ever done it before so it is new.<br/><hr/>
<b>Insole (How I Organize)</b><br/><br/>People say that I am the worst at organizing.<br/>When it comes to homework and test I keep them in the section and binder they belong in.<br/>When it comes to electronic files I have folders after folders to organize files with.<br/>For items i try to keep things as neat as possible but that doesn't usually happen.<br/><hr/>
<b>Laces (Homework Helpers)</b><br/><br/>Things that help me do my homework would be: A Computer, Internet, and People.<br/>A computer and inernet can help me do my homework my researching and word processing.<br/>People help me do homework because they give me ideas and suggestions.<br/><hr/>
<b>Upper (Goals)</b><br/><br/>My all time goal since I was in grade 1 was to be better at Math and English/Language/CORE. <br/> But I also added 'Learn to Code Better' after I started coding and programming in grade 6. <br/>The reason I need to be better at Math is because after I got into the gifted program math was <br/>getting harder and harder and I am not doing the best. <br/> Language has never been my strong point because I came to Canada when I was in grade one so,<br/> English was never my primary language until grade 2.<br/><hr/>
<b>Toe (Strengths)</b><br/><br/>My strengths are mostly in doing crazing things, like what I am doing for this. I can guarantee you that no one has ever given you a Take a Walk in My Shoes project like this.<br/>My strengths are coding and I enjoy doing that a lot. <br/>With coding a lot new things not a lot of people know how to do will be possible like <br/>interactive web elements and windows executable instead of MS Word and PowerPoint presentations.<br/><hr/>
<b>Heel (Challenges)</b><br/><br/>I am not the brightest when it comes to learning.<br/>I am also not the worst so subjects that I am not the best at is Language(Grammar and Spelling) and Art. <br/> I somethings have trouble concentrated while doing homework but I  other than that I have no more challenges.<br/><hr/>
<b>Special Features</b><br/><br/>Well, a computer and a tablet will increase my production rate of homework and work by a lot.<br/>A group of friends or people to chat with can help me learn by taking ideas and knowledge form others.<br/><hr/>
<b>Credits:</b><br/><br/><i>Coding:</i> Harry<br/><i>Photo:</i> Google<br/><br/><hr/>